backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

local_backend: true

collections:
  - name: "beslenme-programlari"
    label: "Beslenme Programları"
    folder: "src/content/beslenme-programlari"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "Program Resmi", name: "thumbnail", widget: "image"}
      - {label: "Kısa Açıklama", name: "description", widget: "text"}
      - {label: "Program Tipi", name: "type", widget: "select", options: ["kilo-verme", "kilo-alma", "koruma", "ozel-durum"]}
      - label: "Program Özellikleri"
        name: "features"
        widget: "list"
        fields:
          - {label: "Özellik", name: "item", widget: "string"}
      - {label: "Program Detayları", name: "content", widget: "markdown"}
      - {label: "Program Süresi", name: "duration", widget: "string"}

  - name: "fit-tarifler"
    label: "Fit Tarifler"
    folder: "src/content/fit-tarifler"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tarif Adı", name: "title", widget: "string"}
      - {label: "Tarif Resmi", name: "thumbnail", widget: "image"}
      - {label: "Kısa Açıklama", name: "description", widget: "text"}
      - {label: "Hazırlama Süresi", name: "prepTime", widget: "string"}
      - {label: "Kalori", name: "calories", widget: "number"}
      - label: "Malzemeler"
        name: "ingredients"
        widget: "list"
      - {label: "Yapılışı", name: "content", widget: "markdown"}