// public/admin/config.yml
backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "saglikli-yasam"
    label: "Sağlıklı Yaşam Yazıları"
    folder: "content/saglikli-yasam"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", format: "YYYY-MM-DD"}
      - {label: "Kapak Resmi", name: "thumbnail", widget: "image"}
      - {label: "Özet", name: "description", widget: "text"}
      - {label: "Kategori", name: "category", widget: "select", options: ["beslenme", "egzersiz", "yasam-tarzi", "zihinsel-saglik"]}
      - {label: "İçerik", name: "body", widget: "markdown"}
      - {label: "Yazar", name: "author", widget: "string", default: "Diyetisyen"}